#!/bin/sh

only_vcs_files()
{
	find $NOVCS \( -type f -or -type d \) -print | filter_ignore | sort
}

# version control systems do not track directories,
# so empty directories must be stored specially.
add_empty_directories()
{
	true
}

default_add_empty_directories()
{
	find $NOVCS -type d -empty -print |
		sort | shellquote | sed -e "s/^/mkdir -p /"
}

# version control system does not track symlinks,
# so they must be stored specially.
add_symlinks()
{
	true
}

add_etckeeper_file()
{
	true
}

get_ignore_file()
{
	echo ""
}

filter_ignorefile()
{
	true
}
